# Generated by Django 5.1.3 on 2026-03-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='serial',
            unique_together={('serial', 'producto')},
        ),
    ]
