# Generated by Django 5.1.3 on 2026-03-09 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0002_alter_serial_serial_alter_serial_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSerialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('serial_asignado', models.ForeignKey(help_text='Serial del producto del cliente', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cliente', to='modulo_gestion_qr.serial')),
                ('serial_maestro', models.ForeignKey(help_text='Serial con template crear_solicitud (el interno)', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_maestro', to='modulo_gestion_qr.serial')),
            ],
            options={
                'unique_together': {('serial_maestro', 'serial_asignado')},
            },
        ),
    ]
