# Generated by Django 5.2.12 on 2026-03-12 16:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0003_asignacionserialcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('en_bodega', 'En Bodega - listo para despacho'), ('despachado', 'Despachado - listo para distribución'), ('Activado', 'Activado - entregado al cliente'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='logos_empresas/'),
        ),
    ]
